version: '3.8'
services:
  appseed-app:
    container_name: appseed_app
    restart: always
    env_file: .env
    build:
      context: .
      network: host
    network_mode: host
    volumes:
      - ./:/app