# Generated by Django 3.2.6 on 2021-10-28 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('codigo_carrera', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('mostrar_correlativas', models.BooleanField()),
            ],
            options={
                'db_table': 'carreras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('codigo_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Competencias',
            fields=[
                ('codigo_competencia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('codigo_plan', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'competencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Correlativasxcantidad',
            fields=[
                ('codigo_correlativaxcantidad', models.AutoField(primary_key=True, serialize=False)),
                ('condicion', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'correlativasxcantidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogSimulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(blank=True, null=True)),
                ('ip', models.CharField(max_length=39)),
                ('session', models.BigIntegerField()),
                ('carrera', models.SmallIntegerField()),
                ('plan', models.CharField(max_length=5)),
                ('orientacion', models.SmallIntegerField()),
                ('ultimo_cuatrimestre_cursado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'log_simulacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('codigo_materia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('carga_semanal', models.IntegerField(blank=True, null=True)),
                ('carga_total', models.IntegerField(blank=True, null=True)),
                ('anual', models.BooleanField(blank=True, null=True)),
                ('abreviatura', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'materias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materiasxorientaciones',
            fields=[
                ('codigo_materiaxorientacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_plan', models.CharField(max_length=6)),
                ('codigo_orientacion', models.IntegerField(blank=True, null=True)),
                ('dictado', models.IntegerField(blank=True, null=True)),
                ('cuatrimestre', models.IntegerField(blank=True, null=True)),
                ('contracursada', models.BooleanField(blank=True, null=True)),
                ('excep_contrac', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'materiasxorientaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Optativas',
            fields=[
                ('codigo_optativa', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_plan', models.CharField(max_length=6)),
                ('codigo_orientacion', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'optativas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titulos',
            fields=[
                ('codigo_titulo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('codigo_plan', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'titulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Correlativas',
            fields=[
                ('codigo_materiaxorientacion', models.OneToOneField(db_column='codigo_materiaxorientacion', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.materiasxorientaciones')),
                ('condicion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'correlativas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Correlativasxcompetencia',
            fields=[
                ('codigo_materiaxorientacion', models.OneToOneField(db_column='codigo_materiaxorientacion', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.materiasxorientaciones')),
            ],
            options={
                'db_table': 'correlativasxcompetencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Correlativasxtitulo',
            fields=[
                ('codigo_materiaxorientacion', models.OneToOneField(db_column='codigo_materiaxorientacion', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.materiasxorientaciones')),
            ],
            options={
                'db_table': 'correlativasxtitulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materiasxcategorias',
            fields=[
                ('codigo_materiaxorientacion', models.OneToOneField(db_column='codigo_materiaxorientacion', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.materiasxorientaciones')),
            ],
            options={
                'db_table': 'materiasxcategorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materiasxcompetencia',
            fields=[
                ('codigo_competencia', models.OneToOneField(db_column='codigo_competencia', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.competencias')),
            ],
            options={
                'db_table': 'materiasxcompetencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materiasxtitulo',
            fields=[
                ('codigo_titulo', models.OneToOneField(db_column='codigo_titulo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.titulos')),
            ],
            options={
                'db_table': 'materiasxtitulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('codigo_carrera', models.OneToOneField(db_column='codigo_carrera', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.carreras')),
                ('codigo_plan', models.CharField(max_length=6)),
                ('resolucion', models.CharField(blank=True, max_length=255, null=True)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'planes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orientaciones',
            fields=[
                ('codigo_carrera', models.OneToOneField(db_column='codigo_carrera', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.planes')),
                ('codigo_plan', models.CharField(max_length=6)),
                ('codigo_orientacion', models.IntegerField()),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'orientaciones',
                'managed': False,
            },
        ),
    ]
